services:
  flask:
    build:
      context: .
    container_name: flaskapp
    expose:
      - "5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  nginx:
    image: nginx:latest
    container_name: nginxproxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
